/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/app/AppAlert.vue')['default']
    AppAlert_backup_1: typeof import('./src/components/app/AppAlert_backup_1.vue')['default']
    AppCard: typeof import('./src/components/app/AppCard.vue')['default']
    AppError: typeof import('./src/components/app/AppError.vue')['default']
    AppGrid: typeof import('./src/components/app/AppGrid.vue')['default']
    AppGrid2: typeof import('./src/components/app/AppGrid2.vue')['default']
    AppLoading: typeof import('./src/components/app/AppLoading.vue')['default']
    AppModal: typeof import('./src/components/app/AppModal.vue')['default']
    AppPagination: typeof import('./src/components/app/AppPagination.vue')['default']
    AppPagination2: typeof import('./src/components/app/AppPagination2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
